### PR TITLE
Test API review change for swagger

### LINKED ISSUE #3019: [Release Planner Test Service - Release Planner Test Product] API Review
New API Review meeting has been requested.

**Service Name**: Release Planner Test Service - Release Planner Test Product
**Review Created By**: Jonathan Cardenas
**Review Date**: 09/27/2023 10:00 AM PT
**Onboarding Record**: https://dev.azure.com/azure-sdk/Release/_workitems/edit/17128
**PR**: https://github.com/test-repo-billy/azure-rest-api-specs/pull/2920
**Hero Scenarios Link**: Not Provided
**Core Concepts Doc Link**: Not Provided

**Description**: TEST from Release Planner

Detailed meeting information and documents provided can be accessed [here](https://web.powerapps.com/apps/fd4a8c57-991f-4489-a16f-1531832d208a?view=edit&event=299fc170-8752-ee11-be6e-000d3a31c83e)
For more information that will help prepare you for this review, the requirements, and office hours, visit the documentation [here](https://aka.ms/azsdk/onboarding/restapischedule)

### PR DESCRIPTION
**Pull request by praveenkuttappan**
Test Swagger API review gen to cover regression test of latest unified pipeline
fix https://github.com/test-repo-billy/azure-rest-api-specs/issues/3019

### CODE REVIEW

**Comment by praveenkuttappan** [comment]
Test request suppression

**Comment by praveenkuttappan** [comment]
Test request suppression updated

**Comment by praveenkuttappan** [comment]
Test PR. Do not merge

**Comment by JonathanCrd** [comment]
Test, requesting suppression

**Pull request closed without merging**
